let btnStart = document.getElementById('start'),
    budgetValue = document.getElementsByClassName('budget-value'),
    dayBudgetValue = document.getElementsByClassName('daybudget-value'),
    levelValue = document.getElementsByClassName('level-value'),
    expensesValue = document.getElementsByClassName('expenses-value'),
    optionalExpensesValue = document.getElementsByClassName('optionalexpenses-value'),
    incomeValue = document.getElementsByClassName('income-value'),
    monthSavingsValue = document.getElementsByClassName('monthsavings-value'),
    yearSavingsValue = document.getElementsByClassName('yearsavings-value'),
    expenses = document.getElementsByClassName('expenses-item'),
    expensesBtn = document.querySelectorAll('#button .expenses-item-btn' ),
    optionalExpensesBtn = document.querySelectorAll('#button .optionalexpenses-btn' ),
    countBudgetBtn = document.querySelectorAll('#button .count-budget-btn' ),
    optionalExpenses = document.querySelectorAll('#input .optionalexpenses-item'),
    income = document.querySelector('#input .choose-income'),
    savings = document.querySelector('#input[id = savings]'),
    chooseSum = document.querySelector('#input[id = sum]'),
    choosePercent = document.querySelector('#input[id = percent]'),
    yearValue = document.querySelector('#input .year-value'),
    montsValue = document.querySelector('#input .month-value'),
    dayValue = document.querySelector('#input .day-value');
    